site_name: Airflow Helper
docs_dir: ./docs

nav:
  - Home: 'overview.md'
  - Automation:
      - Data Dictionary Creation: 'automation/data_dictionary.md'

theme:
  name: material
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - admonition
  - toc:
      permalink: true